project:
  type: website

website:
  site-url: "https://viveks.me/talks"
  title: "Talks"
  navbar:
    right:
      - icon: house-fill
        href: https://viveks.me
      - icon: github
        href: https://github.com/vsrikrish/notebooks
      - icon: rss
        href: index.xml
  search:
    location: navbar
    type: textbox

format:
  html:
    theme: cosmo
    css: css/styles.css


jupyter: julia-1.9